### ISSUE TITLE
No outputs using bank.

### ISSUE THREAD

**Issue by SwordSWD** [mjkzy/t6-zm-chat-bank#3]
I have feds utils plugin and compiled the script using gsc-tool. and i have bank_allow_banking 1 and bank_allow_paying 1 in my dedicated_zm.cfg. There is no output of any of the commands But a bank folder has been created, nothings in it.

**Comment by mjkzy** [comment]
can you show a screenshot of you in-game typing `/balance` in chat?

**Comment by SwordSWD** [comment]
https://user-images.githubusercontent.com/62721069/217989308-9c2ee793-5438-450f-8b54-8c4540eec139.mp4

**Comment by SwordSWD** [comment]
![image](https://user-images.githubusercontent.com/62721069/217989377-4bb7c63c-f1ec-4f5a-8c36-7da770def83c.png)It said it loaded too.

**Comment by mjkzy** [comment]
stupid question, but is your chat on? just gotta ask to make sure lmao

**Comment by SwordSWD** [comment]
Yes it's on lmfao
